#!/usr/bin/env python3

"""System automount support (login-time mounting) for MounThor."""

import logging
import os
import shutil
import subprocess
from pathlib import Path

from .constants import (
    AUTOMOUNT_SERVICE_FILE,
    AUTOMOUNT_SERVICE_NAME,
    HELPER_BIN,
    HELPER_NAME,
    MOUNTHOR_BIN,
    POLKIT_RULE_FILE,
    POLKIT_RULES_DIR,
    USER_SYSTEMD_DIR,
)

LOGGER = logging.getLogger("mounthor")


# ============================================================================
# Helper installation
# ============================================================================

def install_helper() -> bool:
    """Copy the mount helper to ~/.local/bin and make it executable."""
    source = Path(__file__).resolve().parent / "scripts" / HELPER_NAME

    if not source.is_file():
        LOGGER.error(f"Mount helper not found at {source}")
        return False

    try:
        HELPER_BIN.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, HELPER_BIN)
        os.chmod(HELPER_BIN, 0o755)
    except OSError as exc:
        LOGGER.error(f"Failed to install mount helper: {exc}")
        return False

    LOGGER.info(f"Mount helper installed at {HELPER_BIN}")
    return True


# ============================================================================
# Polkit rule management
# ============================================================================

def _polkit_rule_content() -> str:
    """Generate the Polkit rule content for MounThor."""
    username = os.environ.get("USER", "unknown")
    program = str(HELPER_BIN)

    return (
        "// MounThor system automount rule.\n"
        f"// Generated by MounThor for user '{username}'.\n"
        'polkit.addRule(function(action, subject) {\n'
        '    if (\n'
        '        action.id == "org.freedesktop.policykit.exec"\n'
        f'        && action.lookup("program") == "{program}"\n'
        f'        && subject.user == "{username}"\n'
        "    ) {\n"
        "        return polkit.Result.YES;\n"
        "    }\n"
        "});\n"
    )


def ensure_polkit_rule() -> bool:
    """Install the per-user polkit rule (one-time pkexec prompt)."""
    if POLKIT_RULE_FILE.is_file():
        return True

    runtime_dir = os.environ.get("XDG_RUNTIME_DIR", "/tmp")
    tmp_file = Path(runtime_dir) / f".{HELPER_NAME}-rule.tmp"

    try:
        tmp_file.write_text(_polkit_rule_content(), encoding="utf-8")
        os.chmod(tmp_file, 0o600)
    except OSError as exc:
        LOGGER.error(f"Failed to prepare polkit rule file: {exc}")
        return False

    try:
        command = ["pkexec", "install", "-m", "0644", str(tmp_file), str(POLKIT_RULE_FILE)]
        result = subprocess.run(command, capture_output=True, text=True, timeout=120)
    except (subprocess.SubprocessError, OSError) as exc:
        LOGGER.error(f"Polkit rule installation failed: {exc}")
        return False
    finally:
        try:
            tmp_file.unlink()
        except OSError:
            pass

    if result.returncode != 0:
        LOGGER.error(
            f"Polkit rule installation exited {result.returncode}: {result.stderr.strip()}"
        )
        return False

    LOGGER.info(f"Polkit rule installed at {POLKIT_RULE_FILE}")
    return True


# ============================================================================
# Systemd service management
# ============================================================================

def _automount_service_content() -> str:
    """Generate the systemd user service content."""
    return (
        "[Unit]\n"
        "Description=MounThor - automount CIFS shares at login\n"
        "After=default.target\n"
        "\n"
        "[Service]\n"
        "Type=oneshot\n"
        f"ExecStart={MOUNTHOR_BIN} --autostart\n"
        "\n"
        "[Install]\n"
        "WantedBy=default.target\n"
    )


def ensure_automount_service() -> bool:
    """Create and enable the user systemd service."""
    try:
        USER_SYSTEMD_DIR.mkdir(parents=True, exist_ok=True)
        AUTOMOUNT_SERVICE_FILE.write_text(_automount_service_content(), encoding="utf-8")
    except OSError as exc:
        LOGGER.error(f"Failed to write systemd unit: {exc}")
        return False

    try:
        subprocess.run(
            ["systemctl", "--user", "daemon-reload"],
            capture_output=True, text=True, timeout=30, check=True,
        )
        subprocess.run(
            ["systemctl", "--user", "enable", AUTOMOUNT_SERVICE_NAME],
            capture_output=True, text=True, timeout=30, check=True,
        )
    except (subprocess.SubprocessError, OSError) as exc:
        LOGGER.error(f"Failed to enable systemd unit: {exc}")
        return False

    LOGGER.info(f"Systemd user service {AUTOMOUNT_SERVICE_NAME} enabled")
    return True


def disable_automount_service() -> None:
    """Disable the user systemd automount service."""
    try:
        subprocess.run(
            ["systemctl", "--user", "disable", AUTOMOUNT_SERVICE_NAME],
            capture_output=True, text=True, timeout=30,
        )
    except (subprocess.SubprocessError, OSError) as exc:
        LOGGER.warning(f"Failed to disable systemd unit: {exc}")


def ensure_system_automount_ready() -> tuple[bool, str]:
    """Set up helper + polkit rule + service. Returns (ok, message)."""
    if not install_helper():
        return False, "Failed to install the mount helper."

    if not ensure_polkit_rule():
        return False, "Polkit authorization was not granted."

    if not ensure_automount_service():
        disable_automount_service()
        return False, "Failed to enable the systemd service."

    return True, "System automount is ready. Shares will be mounted at login."
